### ISSUE TITLE
remove width x height parameters from streaming URL

### ISSUE THREAD

**Issue by kelvinabrokwa** [wm-robo-ops/pi-clients#3]
I made the video server simpler so you can now just stream to 

```
http://ip_address:port
```

NOT `http://ip_address:port/width/height`

change hither: https://github.com/wm-robo-ops/pi-clients/blob/483d1fa29e0caa158e3df27eaff4eba63135f052/start_video_stream.sh#L9

We can just hard code the dimensions of the video

/cc @ajwells

**Comment by afnanenayet** [comment]
I removed the $height and $width parameters from $ip - should be good
